### ISSUE TITLE
What about a real keep-alive ping avoiding timeout issues?

### ISSUE THREAD

**Issue by frederikhors** [r3labs/sse#101]
I'm using your amazing project on Heroku.

There is a timeout limit there: https://devcenter.heroku.com/articles/request-timeout#long-polling-and-streaming-responses:

> If you’re sending a streaming response, such as with **server-sent events**, you’ll need to detect when the client has hung up, and make sure your app server closes the connection promptly. If the server keeps the connection open for 55 seconds without sending any data, you’ll see a request timeout.

I know in the WebSocket world there is the concept of Keep-Alive ping.

Why don't we add it too?

Example (pseudo code):

```go
go func() { // goroutine to not block the main thread
  for { // infinite loop
    // From https://gist.github.com/akirattii/257d7efc8430c7e3fd0b4ec60fc7a768#file-sse-serverside-example-js-L44-L52
    each 50 seconds send this message to each client if no data has been sent in this interval: // interval is configurable of course
    ":\n\n" // means "comment"
  }
}
```

**What do you think?**

**Comment by frederikhors** [comment]
I'm trying with this code:

```go
go func() {
  for range time.Tick(time.Second * 1) {
    fmt.Println("a second")
    sseServer.Publish("test", &sse.Event{Data: []byte("ping")})
  }
}()
```

using a simple server like this:

```go
httpServer := &http.Server{
  Addr:         ":" + port,
  Handler:      handler,
  ReadTimeout:  "10s",
  WriteTimeout: "10s",
}
```

but it doesn't work. The call is closed after 10 seconds (and 10 pings).

I think it will fail on Heroku too.

Where am I wrong?

**Can we change the timeout for these SSE calls only?**

**Comment by purehyperbole** [comment]
Hey @frederikhors , 

The issue you've described is one of the problems with Server Sent Events. As you rightly point out, websockets handle this issue with ping/pong messages between the client and server.

As SSE is a unidirectional protocol, the client cannot send data to the server after the initial connection has been established.

What you're trying to accomplish can be handled in some way by only setting the `WriteTimeout` value and omitting the `ReadTimeout`, like so:

```go
httpServer := &http.Server{
  Addr:         ":" + port,
  Handler:      handler,
  WriteTimeout: "10s",
}
```

This should cause the server to error when writing to the connection of a disconnected client.

_However_, the caveat to this is that if you are running on linux, `WriteDeadline` is more or less useless for promptly detecting client timeouts, as the call to `write()` on the underlying connection will only queue the data and not send it immediately. From go's perspective, the write is complete so that timer will more or less never fail until that queue has filled up.

It's for this reason if you are using a something like websockets, it's best to use `ReadDeadline` only to detect client disconnects with ping/pong messages, however that's not really an option with SSE.

I guess it all depends on how timely you require the server to react to client disconnects, but if you do require more accurate detection, websockets are probably a better fit for your problem

**Comment by frederikhors** [comment]
I don't need accurate detection, I don't care at all. I'm using it to refresh a dashboard when something happens on server.

I prefer not to use WebSocket for something so easy.

I think I have not explained myself well, because I would like to use ping not so much for detecting disconnected clients but because I would like the connection not to be interrupted (as is happening on Heroku).

## THE SITUATION RIGHT NOW

### LOCALLY

If I remove the `ReadTimeout` field totally on Windows but also on Docker linux container the connection does not stop and everything works fine.

### ON HEROKU

Since on Heroku the connection drops every 55 seconds for that timeout I told you in the first post I tried that loop with that very simple code and it works: the SSE calls are not closed anymore!

### THE REMAINING ISSUE

1. How to have in any case a default `ReadTimeout` for all other calls (not SSE); I think it's best practice to set a default `ReadTimeout`.

In part perhaps I found an answer in this comment on SO: https://stackoverflow.com/questions/69864592/golang-server-default-timeout-with-long-polling-server-sent-event-calls-the-c?noredirect=1#comment123499968_69864592

> 1) To avoid the server-wide write timeout, use an SSE library that hijacks the connection from the net/http server. (2) Use SSE comments as pings.

**What do you think?**

I don't understand the number 1. The second is what I'm currently doing.

**Comment by codewinch** [comment]
@frederikhors there are really two main ways to handle this that I'm aware of:

1. Just don't worry about it -- the client will automatically reconnect (use a polyfill like https://github.com/Yaffle/EventSource if it doesn't, but it should, because automatic reconnection is in the spec: https://html.spec.whatwg.org/multipage/server-sent-events.html#server-sent-events-intro .)
2. Remove the timeouts on platforms that will allow you to.

The second is obviously most efficient, but this will open you up (slightly) to DoS attacks (WS has similar  or even worse risks: https://www.slideshare.net/SergeyShekyan/bay-threat-2012-websockets ) Most platforms (for example, https://github.com/gofiber/fiber/blob/master/app.go#L184 ) already leave the read timeout as unlimited.

For your dashboard use case (or any use case where data is mostly streamed from server to client), it definitely sounds like SSE/eventsource is a great fit, and WS is both overkill and might not even be supported if your client is coming through a proxy (say, at large enterprises).

The connection hijack is a bit more challenging and basically works like a proxy that applies a timeout to some routes and not others, but it's probably worth asking what is your use case where a timeout would be useful? Are you guarding against a DoS attack, or just slow clients? Are you concerned about using up socket connections or file descriptors? Is it feasible to front-end with a proxy like ATC or HA Proxy, so you can configure different routes with different settings?

You might also set the timeout to be very long, such as 10 minutes, and then let the connection automatically reconnect.

**Comment by frederikhors** [comment]
@codewinch thanks! A truly complete and intelligent answer! Now I have to think.

**Comment by codewinch** [comment]
That's excellent! :+1: 

please also close this issue, since this isn't an issue with the library :)
