### ISSUE TITLE
Client receives all previous sent events from server when restarting client. Is it correct behavior?

### ISSUE THREAD

**Issue by Muddz** [r3labs/sse#61]
I have server program which sends events via SSE to the Client program.

Suppose that the Server program has sent forexample 40 events and the client program successfully received all 40 events, but when restarting the Client program (while not restarting the server) it gets all the previous 40 events at once again even though the server didn't send anything.

Is this a behavior that should exist or maybe defined in the SSE specifications? I find it odd

**Comment by purehyperbole** [comment]
Hey! Thanks for raising an issue.

This behaviour is actually part of the SSE spec. Each event sent by the server includes an event ID. This should be tracked by the client so that when it reconnects, it specifies the last event ID seen in the `Last-Event-Id` header. The server will then only send events after that event ID. 

Alternatively, you can disable this by setting the `AutoReplay` variable on the server object to false before starting a steam. 

Hope this helps!

**Comment by Muddz** [comment]
@purehyperbole Thanks setting the flag to `false` helped and I can also see in the logs that it stopped tracking and sending event id's. 

Great work with the library. Keep up the good work and maintance with it
