### ISSUE TITLE
Where does this commit come from?

### ISSUE THREAD

**Issue by FatalReadError** [r3labs/sse#79]
https://github.com/r3labs/sse/commit/a21ea0b822f57bd2725eca14dc75651feced107c

**Comment by purehyperbole** [comment]
Sorry not sure what you mean. That commit is from an unmerged pull request from another repo

**Comment by FatalReadError** [comment]
It is from this repo, r3labs/sse; that's why it begins with `https://github.com/r3labs/sse/commit/`

The only thing that this commit does is change where the files will be pulled from. It appears to be an attack against the repo.

**Comment by FatalReadError** [comment]
Also, I am not watching that repo, but watching only the r3labs one, but this came through in my notifications. I don't receive commit messages from other forks until they are made to the watched repo.

Looking at the other repo, the changes _so far_ seem benign, but that can change... but how did this occur?

**Comment by purehyperbole** [comment]
As far as i'm aware, when a github pull request gets opened, a branch is created on the target repo. 

If you `git ls-remote`, you'll see commit ID's for all pull requests that have been opened so i'm not sure if this is an attack per-se. 
```
641a49cc7d4a4540a615b0633564953dd004c4ea	refs/pull/69/head
df12d65c60e94508b4e797a12f494572ff32acd2	refs/pull/7/head
c3fa507ef0e211cb483bcd420a1d08f24e6c5f4c	refs/pull/74/head
c4a757f15117d1816b2a893d5fc38a440c02d8ce	refs/pull/77/head
a21ea0b822f57bd2725eca14dc75651feced107c	refs/pull/78/head
0203be53760f19d4d3d8437f68932133fade45c2	refs/pull/78/merge
```

The pull request actually includes other changes and its reasonably normal for someone to update the go modules file in their fork and forget to remove that from the PR. However, it won't be merged until the changes to the readme and go.mod has been removed.

I will try look into github's how pull requests work a bit further

**Comment by FatalReadError** [comment]
There doesn't seem to be any open or closed pull request referencing this commit.

My pull request #80 says: "Add more commits by pushing to the patch-1 branch **on FatalReadError/sse**."

**Comment by purehyperbole** [comment]
@FatalReadError Thanks for opening that PR to check. I can actually see your branch when I `git ls-remote`, but not with `git branch -a --contains`. I think we are unable to see it under `r3labs/sse/branches` because its a reference to a branch, rather than an actual branch on the repo. My git expertise isn't too great either, but that seems to be the case. 

For instance, I can check out your pull request by doing `git fetch origin pull/80/head:testbranch` and then `git checkout testbranch` locally.

The origin of that commit comes from:
https://github.com/r3labs/sse/pull/78

more specifically:
https://github.com/r3labs/sse/pull/78/commits/a21ea0b822f57bd2725eca14dc75651feced107c.

I'm able to create a branch from that reference locally the same way I specified above. After doing a bit more reading, i'm mostly confident that its nothing to worry about.

I'll contact the PR's author and request that they remove the go.mod and readme changes from that PR.

**Comment by FatalReadError** [comment]
*whew*, sorry for raising the alarm! Looks like you're right on the money on that. Thanks, closing this!

**Comment by FatalReadError** [comment]
What's strange about this: I received a commit notification from *this* repo for the above commit. I didn't think individual commits were notified.

However, the other commit in this pull looks good to me.

**Comment by purehyperbole** [comment]
Yeah, thats definitely strange. I'm not sure whether thats a bug with github notifications? Have you received anything for any other PR's opened recently?

**Comment by FatalReadError** [comment]
No, but I only started watching this repo fairly recently. I also didn't
receive any notification of the /other/ commit in this PR. And I didn't
receive a notification of my test PR, but perhaps that was because I was
the submitter.

**Comment by FatalReadError** [comment]
That is so strange. I just got notification of my reply. I agree -- there's definitely some bugs in Github notifications.
